--- #YAML:1.0
name:               bugzillareport
version:            1.02
abstract:           Prints text list of bugzilla bugs to stdout suitable for non IT people
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTML::Template:   2.8
    LEOCHARRE::CLI2:  1.07
    LEOCHARRE::Dir:   1.07
    Smart::Comments:  1
    Test::Simple:     0
    Text::Flowed:     0.14
    Time::Format:     1.09
    YAML::DBH:        1.06
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
